# Configuracion SMTP de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unirmaestria56@gmail.com
spring.mail.password=vtbl htdf asua zbbe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# URL de conexion a RDS
spring.datasource.url=jdbc:mysql://seguridad-db.c3r8b4fgfuxx.us-east-1.rds.amazonaws.com:3306/seguridad_db

# Usuario y contrasena que configuraste al crear la instancia RDS
spring.datasource.username=aviera
spring.datasource.password=andresviera

# Driver y configuracion de JPA/Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
